version: '3.8'

services:
  frontend:
    build: ./project-root/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  features:
    build: ./project-root/features
    container_name: features
    ports:
      - "5000:5000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

